name: CICD

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: docker build -f Dockerfile -t searadejesus/searafront:latest .
            - name: Publish image to docker hub
              run: docker push searadejesus/searafront:latest 

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull searadejesus/searafront:latest
            
            - name: Run docker container
              run: docker run -it -p 4001:3000 -e BACKEND_URL=${{secrets.BACKEND_URL}} -e CLIENT_ID=${{secrets.CLIENT_ID}} -e CLIENT_SECRET=${{secrets.CLIENT_SECRET}} --name searafront searadejesus/searafront:latest