name: CICD

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              env:
                BACKEND_URL: '${{secrets.BACKEND_URL}}'
                CLIENT_ID: '${{secrets.CLIENT_ID}}'
                CLIENT_SECRET: '${{secrets.CLIENT_SECRET}}'
              run: docker build -f Dockerfile -t searadejesus/searafront:latest .
            - name: Publish image to docker hub
              run: docker push searadejesus/searafront:latest 

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              env:
                BACKEND_URL: '${{secrets.BACKEND_URL}}'
                CLIENT_ID: '${{secrets.CLIENT_ID}}'
                CLIENT_SECRET: '${{secrets.CLIENT_SECRET}}'
              run: docker pull searadejesus/searafront:latest
            
            